options:
  plugin:
    default: ovs
    type: string
    description: |
      Network configuration plugin to use to manage
      the quantum network across quantum and nova-compute
      nodes. Supported values include:
      .
        ovs - OpenVSwitch
  ext-port:
    type: string
    description: |
      External port to use for routing of instance
      traffic to the external public network.
  region:
    type: string
    default: RegionOne
    description: |
      OpenStack region that this quantum service supports.
  openstack-origin:
    type: string
    description: |
      Optional configuration to support use of additional sources such as:
      .
        - ppa:myteam/ppa
        - cloud:precise-folsom/proposed
        - cloud:precise-folsom
        - deb http://my.archive.com/ubuntu main|KEYID
