options:
  plugin:
    default: ovs
    type: string
    description: |
      Network configuration plugin to use for quantum.
      Supported values include:
      .
        ovs - OpenVSwitch
  ext-port:
    type: string
    description: |
      External port to use for routing of instance
      traffic to the external public network.
  openstack-origin:
    type: string
    default: cloud:precise-folsom
    description: |
      Optional configuration to support use of additional sources such as:
      .
        - ppa:myteam/ppa
        - cloud:precise-folsom/proposed
        - cloud:precise-folsom
        - deb http://my.archive.com/ubuntu main|KEYID
  # HA configuration settings
  ha-bindiface:
    type: string
    default: eth0
    description: |
      Default network interface on which HA cluster will bind to communication
      with the other members of the HA Cluster.
  ha-mcastport:
    type: int
    default: 5405
    description: |
      Default multicast port number that will be used to communicate between
      HA Cluster nodes.
